# Google Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.api',
      '-t', 'gcr.io/$PROJECT_ID/abbanoa-api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/abbanoa-api:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/abbanoa-api']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'abbanoa-api',
      '--image', 'gcr.io/$PROJECT_ID/abbanoa-api:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=abbanoa-464816,BIGQUERY_PROJECT_ID=abbanoa-464816,BIGQUERY_DATASET_ID=water_infrastructure,BIGQUERY_LOCATION=EU',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '60',
      '--concurrency', '100',
      '--max-instances', '10',
      '--min-instances', '1'
    ]

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _REGION: europe-west1
  _SERVICE: abbanoa-api

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/abbanoa-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/abbanoa-api:latest'