version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: abbanoa-api:latest
    container_name: abbanoa-api
    ports:
      - "8000:8000"
    environment:
      # Google Cloud settings
      - GOOGLE_CLOUD_PROJECT=abbanoa-464816
      - BIGQUERY_PROJECT_ID=abbanoa-464816
      - BIGQUERY_DATASET_ID=water_infrastructure
      - BIGQUERY_LOCATION=EU
      
      # API settings
      - LOG_LEVEL=INFO
      - API_V1_PREFIX=/api/v1
      
      # Anomaly detection settings
      - ANOMALY_Z_SCORE=3.0
      - ANOMALY_MIN_POINTS=10
      - ANOMALY_WINDOW_HOURS=24
      
    volumes:
      # Mount Google Cloud credentials if using service account
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/credentials.json:ro
      # Mount gcloud config for application default credentials
      - ~/.config/gcloud:/home/apiuser/.config/gcloud:ro
      
    # Set credentials path if mounted
    command: >
      sh -c "
        if [ -f /app/credentials.json ]; then
          export GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
        fi &&
        uvicorn src.presentation.api.app:app --host 0.0.0.0 --port 8000 --reload
      "
      
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Streamlit dashboard container
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    image: abbanoa-dashboard:latest
    container_name: abbanoa-dashboard
    ports:
      - "8502:8502"
    environment:
      - GOOGLE_CLOUD_PROJECT=abbanoa-464816
      - API_BASE_URL=http://api:8000
    volumes:
      # Mount Google Cloud credentials
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/credentials.json:ro
      - ~/.config/gcloud:/home/appuser/.config/gcloud:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - full  # Only start with --profile full

networks:
  default:
    name: abbanoa-network