#!/bin/bash
# Script to help request organization policy exception

echo "=== Organization Policy Exception Request ==="
echo ""
echo "To enable service account key creation for this project, send this request"
echo "to your Google Cloud Organization Administrator:"
echo ""
echo "----------------------------------------"
echo "Subject: Request for Service Account Key Creation Exception"
echo ""
echo "Project ID: abbanoa-464816"
echo "Project Name: Abbanoa Water Infrastructure"
echo ""
echo "Request: Please add an exception to the organization policy"
echo "'constraints/iam.disableServiceAccountKeyCreation' for this project."
echo ""
echo "Justification:"
echo "- Need to authenticate BigQuery access from Docker containers"
echo "- Processing water infrastructure sensor data"
echo "- Service runs in isolated containers without GCP metadata service"
echo ""
echo "Service Account: bigquery-service-account@abbanoa-464816.iam.gserviceaccount.com"
echo "Existing Key ID: 265ff48267cf477ee0e93f66fb5f2bb5dcf5d570 (created 2025-07-07)"
echo ""
echo "Temporary Exception Requested: 30 days"
echo "Long-term Solution: Will migrate to Workload Identity Federation"
echo "----------------------------------------"
echo ""
echo "Once approved, run:"
echo "  gcloud iam service-accounts keys create bigquery-service-account-key.json \\"
echo "    --iam-account=bigquery-service-account@abbanoa-464816.iam.gserviceaccount.com"
echo ""